# Generated by Django 4.0.5 on 2022-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discount_price_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mob',
            field=models.CharField(default=91, max_length=12),
        ),
    ]
